// <auto-generated />
using System;
using MaaPateshwariUniversity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaaPateshwariUniversity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104083314_AddNewTables")]
    partial class AddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.AccreditationAgency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("AgencyCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AgencyId");

                    b.HasIndex("AgencyCode")
                        .IsUnique();

                    b.ToTable("AccreditationAgencies");

                    b.HasData(
                        new
                        {
                            AgencyId = 1,
                            AgencyCode = "NAAC",
                            AgencyName = "National Assessment and Accreditation Council",
                            IsActive = true
                        },
                        new
                        {
                            AgencyId = 2,
                            AgencyCode = "AICTE",
                            AgencyName = "All India Council for Technical Education",
                            IsActive = true
                        },
                        new
                        {
                            AgencyId = 3,
                            AgencyCode = "NCTE",
                            AgencyName = "National Council for Teacher Education",
                            IsActive = true
                        },
                        new
                        {
                            AgencyId = 4,
                            AgencyCode = "PCI",
                            AgencyName = "Pharmacy Council of India",
                            IsActive = true
                        },
                        new
                        {
                            AgencyId = 5,
                            AgencyCode = "BCI",
                            AgencyName = "Bar Council of India",
                            IsActive = true
                        },
                        new
                        {
                            AgencyId = 6,
                            AgencyCode = "UGC",
                            AgencyName = "University Grants Commission",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.Country", b =>
                {
                    b.Property<ushort>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = (ushort)1,
                            CountryName = "India",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.CourseMaster", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CourseId");

                    b.ToTable("CourseMasters");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.DisciplineMaster", b =>
                {
                    b.Property<short>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<short>("StreamId")
                        .HasColumnType("smallint");

                    b.HasKey("DisciplineId");

                    b.ToTable("DisciplineMasters");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.District", b =>
                {
                    b.Property<uint>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("StateId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("DistrictId");

                    b.HasIndex("StateId", "DistrictName")
                        .IsUnique();

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1u,
                            DistrictName = "Balrampur",
                            IsActive = true,
                            StateId = (ushort)1
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.GovernmentCategory", b =>
                {
                    b.Property<ushort>("GovernmentCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("GovernmentCategoryId"));

                    b.Property<string>("GovernmentCategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GovernmentCategoryId");

                    b.ToTable("GovernmentCategories");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.InstitutionCategory", b =>
                {
                    b.Property<ushort>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoryId");

                    b.ToTable("InstitutionCategories");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.LocationType", b =>
                {
                    b.Property<byte>("LocationTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LocationTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LocationTypeId");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            LocationTypeId = (byte)1,
                            IsActive = true,
                            LocationTypeName = "Urban"
                        },
                        new
                        {
                            LocationTypeId = (byte)2,
                            IsActive = true,
                            LocationTypeName = "Rural"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.MajorMinorMapping", b =>
                {
                    b.Property<long>("MajorMinorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MajorMinorId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("MajorProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("MinorProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("MajorMinorId");

                    b.ToTable("MajorMinorMappings");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.ManagementType", b =>
                {
                    b.Property<ushort>("ManagementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("ManagementTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ManagementTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ManagementTypeId");

                    b.ToTable("ManagementTypes");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.MinorityType", b =>
                {
                    b.Property<ushort>("MinorityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("MinorityTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MinorityTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MinorityTypeId");

                    b.ToTable("MinorityTypes");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.NEPComponentType", b =>
                {
                    b.Property<byte>("ComponentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("ComponentTypeId"));

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ComponentTypeId");

                    b.ToTable("NEPComponentTypes");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.Organization", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrganizationId"));

                    b.Property<ushort?>("CategoryId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<ushort>("CountryId")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<uint?>("DistrictId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ExtensionNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("longtext");

                    b.Property<string>("Fax")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("GeoLatitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("GeoLongitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<ushort?>("GovernmentCategoryId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("InstituteCode")
                        .HasColumnType("longtext");

                    b.Property<string>("InstituteName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAffiliated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAutonomous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMinorityInstitution")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("longtext");

                    b.Property<byte?>("LocationTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort?>("ManagementTypeId")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("MinorityTypeId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameHi")
                        .HasColumnType("longtext");

                    b.Property<string>("NameLocal")
                        .HasColumnType("longtext");

                    b.Property<string>("OfficialEmail")
                        .HasColumnType("longtext");

                    b.Property<byte>("OrganizationTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("OuCategoryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("ParentOrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pincode")
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .HasColumnType("longtext");

                    b.Property<ushort?>("StateId")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte?>("StatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<ushort?>("SubTypeId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterLink")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.Property<ushort?>("YearOfEstablishment")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.OrganizationAccreditation", b =>
                {
                    b.Property<long>("OrganizationAccreditationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrganizationAccreditationId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GradeOrStatus")
                        .HasColumnType("longtext");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrganizationAccreditationId");

                    b.ToTable("OrganizationAccreditations");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.OrganizationProgram", b =>
                {
                    b.Property<long>("OrganizationProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("OrganizationProgramId"));

                    b.Property<string>("AffiliationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IntakeCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationProgramId");

                    b.ToTable("OrganizationPrograms");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.OrganizationType", b =>
                {
                    b.Property<byte>("OrganizationTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrganizationTypeId");

                    b.ToTable("OrganizationTypes");

                    b.HasData(
                        new
                        {
                            OrganizationTypeId = (byte)1,
                            IsActive = true,
                            TypeName = "University"
                        },
                        new
                        {
                            OrganizationTypeId = (byte)2,
                            IsActive = true,
                            TypeName = "Affiliated College"
                        },
                        new
                        {
                            OrganizationTypeId = (byte)3,
                            IsActive = true,
                            TypeName = "Office"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.OuCategory", b =>
                {
                    b.Property<byte>("OuCategoryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OuCategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OuCategoryId");

                    b.ToTable("OuCategories");

                    b.HasData(
                        new
                        {
                            OuCategoryId = (byte)1,
                            IsActive = true,
                            OuCategoryName = "PLAN"
                        },
                        new
                        {
                            OuCategoryId = (byte)2,
                            IsActive = true,
                            OuCategoryName = "NON-PLAN"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.ProgramCourseMapping", b =>
                {
                    b.Property<long>("ProgramCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProgramCourseId"));

                    b.Property<byte>("ComponentTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<byte>("SemesterId")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ProgramCourseId");

                    b.ToTable("ProgramCourseMappings");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.ProgramMaster", b =>
                {
                    b.Property<long>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProgramId"));

                    b.Property<string>("DegreeLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("DisciplineId")
                        .HasColumnType("smallint");

                    b.Property<byte>("DurationYears")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("ProgramMasters");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RefreshTokenId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "UniversityAdmin"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "CollegeAdmin"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.SemesterMaster", b =>
                {
                    b.Property<byte>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("SemesterId"));

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SemesterId");

                    b.ToTable("SemesterMasters");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.State", b =>
                {
                    b.Property<ushort>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("StateId"));

                    b.Property<ushort>("CountryId")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = (ushort)1,
                            CountryId = (ushort)1,
                            IsActive = true,
                            StateName = "Uttar Pradesh"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.StatusMaster", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusId");

                    b.ToTable("StatusMasters");

                    b.HasData(
                        new
                        {
                            StatusId = (byte)1,
                            IsActive = true,
                            StatusName = "Published"
                        },
                        new
                        {
                            StatusId = (byte)2,
                            IsActive = true,
                            StatusName = "Draft"
                        });
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.StreamMaster", b =>
                {
                    b.Property<short>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("StreamId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StreamId");

                    b.ToTable("StreamMasters");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.SubInstitutionType", b =>
                {
                    b.Property<ushort>("SubTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("SubTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubTypeId");

                    b.ToTable("SubInstitutionTypes");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("OrganizationId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MaaPateshwariUniversity.Domain.Entities.State", b =>
                {
                    b.HasOne("MaaPateshwariUniversity.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
